// web-components/traffic-lights.js
class TrafficLightsBulb extends HTMLElement {
}
customElements.define('traffic-lights-bulb', TrafficLightsBulb);

class TrafficLights extends HTMLElement {
  constructor() {
    super();
    this.timerEnabled = false;
    this.phaseChangeTime = this.getLitBulbDuration();
    this.ticker = setInterval(()=>this.tick(), 1000);
  }

  getLights(){
    return Array.from(this.querySelectorAll('traffic-lights-bulb'));
  }

  getIndexOfLitBulb(){
    const bulbs = this.getLights();
    for(let i = 0; i < bulbs.length; i++){
      if(bulbs[i].getAttribute('on')) return i;
    };
    return false;
  }

  getLitBulb(){
    return this.querySelector('traffic-lights-bulb[on]');
  }

  getLitBulbDuration(){
    const DEFAULT_DURATIONS = {
      red: 3,
      yellow: 1,
      green: 12
    }
    const currentBulb = this.getLitBulb();
    return parseInt(currentBulb.getAttribute('duration')) || DEFAULT_DURATIONS[currentBulb.getAttribute('color')];
  }

  advanceSequence(){
    const bulbs = this.getLights();
    const currentBulbIndex = this.getIndexOfLitBulb();
    const nextBulbIndex = (currentBulbIndex + 1) % bulbs.length;
    bulbs[currentBulbIndex].removeAttribute('on');
    bulbs[nextBulbIndex].setAttribute('on', true);
    this.phaseChangeTime = this.getLitBulbDuration();
    this.updateTimer();
  }

  createControls(){
    const controlsElement = document.createElement('ul');
    controlsElement.classList.add('traffic-lights__controls');

    controlsElement.innerHTML = `
      <li><button class="traffic-lights__controls__advance">Advance to next light</button></li>
      <li><button class="traffic-lights__controls__toggle-timer">Toggle timer</button></li>
    `;

    controlsElement.addEventListener('click', e=>{
      const button = e.target.closest('button');
      if(!button) return;
      if(button.classList.contains('traffic-lights__controls__advance')){
        this.advanceSequence();
      } else if(button.classList.contains('traffic-lights__controls__toggle-timer')){
        this.timerEnabled = !this.timerEnabled;
        this.updateTimer();
      }
    })

    this.after(controlsElement);
  }

  tick(){
    if(!this.timerEnabled) return;
    this.phaseChangeTime--;
    if(this.phaseChangeTime <= 0) this.advanceSequence();
    this.updateTimer();
  }

  createTimer(){
    this.timerElement = document.createElement('div');
    this.timerElement.classList.add('traffic-lights__timer');
    this.after(this.timerElement);
    this.updateTimer();
  }

  updateTimer(){
    this.timerElement.innerHTML = `
      Timer: ${this.phaseChangeTime}
      ${this.timerEnabled ? ' (running)' : ' (paused)'}
    `;
  }

  connectedCallback(){
    if(this.getAttribute('controls')) this.createControls();
    if(this.getAttribute('timer')) this.createTimer();
  }
}
customElements.define('traffic-lights', TrafficLights);

// react/src/traffic-lights.js
import { useEffect, useState, useCallback } from 'react';

import { Bulb } from './bulb';

export default function TrafficLights({ showTimer, showControls, durations }) {
  const DEFAULT_DURATIONS = { red: 3, yellow: 1, green: 12 };
  let lightDurations = Object.assign(DEFAULT_DURATIONS, durations);

  const [light, setLight] = useState('green');
  const [timerEnabled, setTimerEnabled] = useState(false);
  const [phaseChangeTime, setPhaseChangeTime] = useState(lightDurations.green);

  const advanceSequence = useCallback(()=>{
    switch (light) {
      case 'green':
        setLight('red');
        setPhaseChangeTime(lightDurations.red);
        return;
      case 'red':
        setLight('yellow');
        setPhaseChangeTime(lightDurations.yellow);
        return;
      default:
        setLight('green');
        setPhaseChangeTime(lightDurations.green);
    }
  }, [light, lightDurations]);

  useEffect(() => {
    const ticker = setInterval(() => {
      if(!timerEnabled) return;
      const newPhaseChangeTime = phaseChangeTime - 1;
      setPhaseChangeTime(newPhaseChangeTime);
      if(newPhaseChangeTime <= 0) advanceSequence();
    }, 1000);

    return () => clearInterval(ticker);
  }, [timerEnabled, phaseChangeTime, advanceSequence]);

  return (
    <>
      <div className="traffic-lights">
        <Bulb color="red" on={ 'red' === light } />
        <Bulb color="yellow" on={ 'yellow' === light } />
        <Bulb color="green" on={ 'green' === light } />
      </div>
      {showTimer && (
        <div className="traffic-lights__timer">
          Timer: {phaseChangeTime}
          {timerEnabled ? ' (running)' : ' (paused)'}
        </div>
      )}
      {showControls && (
        <ul className="traffic-lights__controls">
          <li><button onClick={ () => advanceSequence() }>Advance to next light</button></li>
          <li><button onClick={ () => setTimerEnabled(!timerEnabled) }>Toggle timer</button></li>
        </ul>
      )}
    </>
  );
}
